apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rating-default
  namespace: default
spec:
  destination:
    name: rating
  precedence: 1
  route:
  - labels:
      version: v1
