---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: product-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: beershop.local
    http:
      paths:
      - backend:
          serviceName: product-service
          servicePort: 8080
        path: /products/.*
status:
  loadBalancer: {}
